apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wnck
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wnck
    app.kubernetes.io/part-of: byoc-app-jyte
  name: wnck
spec:
  rules:
  - host: wnck-byoc-vagc-tenant.apps.2e9334e35120771c894a.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: wnck
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
